// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqzjliletbnulbcamjoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxempsaWxldGJudWxiY2Ftam9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTc1MDgsImV4cCI6MjA2OTI3MzUwOH0.chGY2Mme0W5LC2gKC03ui5suShzBQl1ufW1BpvYHxnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});